image: node:14

cache:
  paths:
    - node_modules/

variables:
  NOW_BUILD_PARAMS: '--confirm'

stages:
  - test
  - deploy 

test:
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  stage: test
  script: yarn jest --coverage
  only:
    - merge_requests

before_script:
  - npm install -g vercel --silent --unsafe-perm

staging:
  stage: deploy
  script:
    - echo "Deploying app to [staging] environment"
    - VERCEL_ORG_ID=$VERCEL_ORG_ID
      VERCEL_PROJECT_ID=$STG_VERCEL_PROJECT_ID
      vercel --token=$NOW_DEPLOY_TOKEN $NOW_BUILD_PARAMS --prod --build-env CI_COMMIT_SHA=$CI_COMMIT_SHORT_SHA
  environment:
    name: production
    url: https://staging.productfinder.app
  only:
    - staging

production:
  stage: deploy
  script:
    - echo "Deploying app to [production] environment"
    - VERCEL_ORG_ID=$VERCEL_ORG_ID
      VERCEL_PROJECT_ID=$PROD_VERCEL_PROJECT_ID
      vercel --token=$NOW_DEPLOY_TOKEN $NOW_BUILD_PARAMS --prod --build-env CI_COMMIT_SHA=$CI_COMMIT_SHORT_SHA
  environment:
    name: production
    url: https://productfinder.app
  only:
    - master 
